# Generated by Django 4.1.7 on 2023-03-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='Login.solicitud'),
        ),
    ]
